package com.example.boanergepro.pagomovil.resources;

/**
 * Created by boanergepro on 18/04/18.
 */

public class Bank {
    public static final String[] bancos = {
            "BANCO DE VENEZUELA S.A.I.C.A.",
            "100% BANCO",
            "ABN AMRO BANK",
            "BANCAMIGA BANCO MICROFINANCIERO, C.A.",
            "BANCO ACTIVO BANCO COMERCIAL, C.A.",
            "BANCO AGRICOLA",
            "BANCO BICENTENARIO",
            "BANCO CARONI, C.A. BANCO UNIVERSAL",
            "BANCO DE DESARROLLO DEL MICROEMPRESARIO",
            "BANCO DEL CARIBE C.A.",
            "BANCO DEL PUEBLO SOBERANO C.A.",
            "BANCO DEL TESORO",
            "BANCO ESPIRITO SANTO, S.A.",
            "BANCO EXTERIOR C.A.",
            "BANCO INDUSTRIAL DE VENEZUELA.",
            "BANCO INTERNACIONAL DE DESARROLLO, C.A.",
            "BANCO MERCANTIL C.A.",
            "BANCO NACIONAL DE CREDITO",
            "BANCO OCCIDENTAL DE DESCUENTO.",
            "BANCO PLAZA",
            "BANCO PROVINCIAL BBVA",
            "BANCO VENEZOLANO DE CREDITO S.A.",
            "BANCRECER S.A. BANCO DE DESARROLLO",
            "BANESCO BANCO UNIVERSAL",
            "BANFANB",
            "BANGENTE",
            "BANPLUS BANCO COMERCIAL C.A",
            "CITIBANK",
            "CORP BANCA",
            "DELSUR BANCO UNIVERSAL",
            "FONDO COMUN",
            "INSTITUTO MUNICIPAL DE CREDITO POPULAR",
            "MIBANCO BANCO DE DESARROLLO, C.A.",
            "SOFITASA"
    };
    public static final String[] codes = {
            "0102",
            "0156",
            "0196",
            "0172",
            "0171",
            "0166",
            "0175",
            "0128",
            "0164",
            "0114",
            "0149",
            "0163",
            "0176",
            "0115",
            "0003",
            "0173",
            "0105",
            "0191",
            "0116",
            "0138",
            "0108",
            "0104",
            "0168",
            "0134",
            "0177",
            "0146",
            "0174",
            "0190",
            "0121",
            "0157",
            "0151",
            "0601",
            "0169",
            "0137"
    };
}
